baseURL: "https://jasmeetkaur9.github.io/" 
title: Jasmeet Kaur
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name : About
          url : about/
          weight : 2
        - name: Papers
          url: papers/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Blog
          url: blog/
          weight: 6

params:
    description: I am graduate student at UT Austin. My primary research interest is Reinforcement Learning with a focus on methods for generalization, adaptability and sample efficiency."
    author: Jasmeet Kaur
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jasmeet Kaur
          subtitle: "I am a graduate student at UT Austin. My primary research interest is Reinforcement Learning with a focus on methods for generalization, adaptability and sample efficiency. "
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jasmeet Kaur
          buttons:
            - name: About
              url: about/
              weight: 2
            - name: Papers
              url: papers/
              weight: 2
            - name: Projects
              url: projects/
              weight: 3
            - name: Blog
              url: blog/
              weight: 6

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jkaur@cs.utexas.edu
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: GitHub
          url: https://github.com/jasmeetkaur9
        - name: Twitter
          url: https://twitter.com/jasmeeet9

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jasmeet Kaur"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2